h/w 1
fackloar/ASP.NETCoreWEBApp pull request #1
Opened 2021-06-24 19:31 UTC by fackloar

2021-07-05 14:59 UTC, vladimir-shmidt requested changes
в целом норм
но нужно улучшить код

2021-07-05 14:59 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +            File.WriteAllText(fileName, strFile);
операция записи в файл такая же асинхронная операция как и работа с сетью стоит передалеть

2021-07-05 14:59 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +            strFile = Regex.Replace(strFile, ":", "");
во первых здесь изменяется одна и таже строка при этом она создается каждый раз новая что делает нагрузку на сборщик мусора
во вторых Replace можно сделать один раз написав правильное выражение
в третьих для данного случая нужно обойтись без решулярок и работы со строками - вместо этого следует использовать сериализацию JSON - https://docs.microsoft.com/ru-ru/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0

2021-07-05 14:59 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +                File.AppendAllText(file, post);
самая важная операция с записью делается синхронно - нужно сделать асинхронно. Для этого есть соответствующие примитивы работы с файлами

2021-07-05 14:59 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +                await Task.Delay(1000);
не нужно делать Delay он тут совсем не нужен

2021-07-05 14:59 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +        static List<string> text = new List<string>();
использование глобального состояния плохой тон

2021-07-05 14:59 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +        static List<string> text = new List<string>();
стоит передавать скаченные результаты непсредственно в место использлования

2021-07-06 22:03 UTC, fackloar commented
> в целом норм
> но нужно улучшить код

Постарался исправить все замечания, спасибо!

2021-07-12 10:02 UTC, vladimir-shmidt approved these changes
с асинком разобрался
в целом задача выполнена.
Можно лучше, пробуйц писать больше кода и читать код других проектов что бы выработать стиль и понимание по организации  итд

2021-07-12 10:02 UTC, vladimir-shmidt commented on Lesson1/Program.cs
> +            foreach (Post post in posts)
здесь все равно продолжается использоваться глобальное состояние в виде posts. Лучше передавать данные напрямую в метод через аргументы

2021-07-12 21:26 UTC, merged